### ISSUE TITLE
"Request failed - Exceeded the daily Google Photos API limit." happens before an album is selected

### ISSUE THREAD

**Issue by leathej1** [opus1269/screensaver#1]
Not sure if this is due to other folks already selecting up their albums or not, but I cannot proceed in selecting my albums.

**Comment by opus1269** [comment]
Trying to fix it. Hang in there for a while. Hope for the best, prepare for
the worst, ha ha.  If I can't fix it, I'll have to remove it from the store.

**Comment by leathej1** [comment]
smh Google. What will they destroy next.

**Comment by opus1269** [comment]
Yeah. For all of Microsoft's problems they always cared about backwards
compatibility. Not so with Google.

**Comment by opus1269** [comment]
Fixed

**Comment by opus1269** [comment]
closing
